USE join_sql;
SELECT*FROM EMP;
SELECT*FROM DEPT;
SELECT*FROM SALGRADE;

-- 1-10: Employee and Salary Aggregations 

-- 1. Total Salary by Job 
SELECT JOB,SUM(SAL) 
FROM EMP
GROUP BY JOB;

-- 2. Average Salary by Department 
SELECT D.DNAME AS DEPARTMENT_NAME,ROUND(AVG(E.SAL)) AS AVERAGE_SALARY
FROM DEPT AS D
RIGHT JOIN EMP AS E
ON D.DEPTNO=E.DEPTNO
GROUP BY D.DNAME;

-- 3. Minimum Salary by Manager 
SELECT M.ENAME AS MANAGER,MIN(E.SAL) AS MIN_SALARY
FROM EMP AS E
JOIN EMP AS M
ON E.MGR=M.EMPNO
GROUP BY M.ENAME; 

-- 4. Maximum Salary by Job  
SELECT JOB,MAX(SAL) AS MAX_SALARY
FROM EMP
GROUP BY JOB;

-- 5. Count of Employees by Department
SELECT D.DNAME AS DEPARTMENT,COUNT(E.EMPNO) AS EMPLOYEE_NUMBER
FROM DEPT AS D
RIGHT JOIN EMP AS E
ON D.DEPTNO=E.DEPTNO
GROUP BY D.DNAME;

-- 6. Total Commission by Job  
SELECT JOB,SUM(COMM) AS TOTAL_COMMISSION
FROM EMP
GROUP BY JOB;

-- 7. Employee Count by Manager 
SELECT M.ENAME AS MANAGER,COUNT(E.EMPNO) AS NUMBER_OF_EMPLOYEE
FROM EMP AS E
JOIN EMP AS M
ON E.MGR=M.EMPNO
GROUP BY M.ENAME;

-- 8. Departments with Total Salary Greater Than 5000 
SELECT D.DNAME AS DEPARTMENT,SUM(E.SAL) AS TOTAL_SALARY
FROM DEPT AS D
RIGHT JOIN EMP AS E
ON D.DEPTNO=E.DEPTNO
GROUP BY D.DNAME
HAVING SUM(E.SAL) >5000;

-- 9. Jobs with Average Salary Between 1000 and 3000
SELECT JOB,AVG(SAL) AS AVG_SALARY
FROM EMP
WHERE SAL BETWEEN 1000 AND 3000
GROUP BY JOB;

SELECT JOB,AVG(SAL) AS AVG_SALARY
FROM EMP
GROUP BY JOB
HAVING AVG(SAL) BETWEEN 1000 AND 3000;
  
-- 10. Employees with Null Commissions Grouped by Job 
SELECT JOB,COUNT(EMPNO) AS NO_OF_EMPLOYEE
FROM EMP
WHERE COMM IS NULL
GROUP BY JOB
ORDER BY COUNT(EMPNO) DESC;

-- 11-20: Employee and Hire Date  
-- 11. Earliest Hire Date by Department
SELECT D.DNAME AS DEPARTMENT, E.HIREDATE AS HIREDATE
FROM DEPT D
LEFT JOIN EMP E
ON D.DEPTNO=E.DEPTNO
ORDER BY HIREDATE DESC;

  
-- 12. Latest Hire Date by Job 
SELECT JOB,MAX(HIREDATE) AS HIREDATE
FROM EMP
GROUP BY JOB
ORDER BY JOB;

-- 13. Total Employees Hired After 1981 Grouped by Manager 
SELECT M.ENAME AS MANAGER,E.ENAME AS EMPLOYEE,SUM(E.EMPNO) 
FROM EMP AS E
JOIN EMP AS M
ON E.MGR=M.EMPNO
WHERE YEAR(E.HIREDATE) >1981
GROUP BY M.ENAME,E.ENAME
ORDER BY COUNT(E.ENAME) DESC;
 
-- 14. Average Salary of Employees Hired After 1981
SELECT ENAME AS EMPLOYEE ,AVG(SAL) AS AVERAGE_SALARY 
FROM EMP
WHERE YEAR(HIREDATE)>1981
GROUP BY ENAME;
 
-- 15. Number of Employees Hired Per Job  
SELECT JOB,COUNT(EMPNO) AS EMPLOYEE_NUMBER
FROM EMP
GROUP BY JOB;

-- 16. Departments with Maximum Hire Date Before 1983  
SELECT D.DNAME AS DEPARTMENT,MAX(E.HIREDATE) AS MAX_HIREDATE
FROM EMP E
RIGHT JOIN DEPT D
ON E.DEPTNO=D.DEPTNO
WHERE YEAR(E.HIREDATE)<1983
GROUP BY D.DNAME
HAVING MAX(E.HIREDATE) IS NOT NULL;

-- 17. Managers with Employees Hired After 1982 
SELECT M.ENAME AS MANAGER,E.HIREDATE AS HIREDATE
FROM EMP E
JOIN EMP M
ON E.MGR=M.EMPNO
WHERE YEAR(E.HIREDATE) >1982; 

-- 18. Jobs with Total Salary Above 10000 
SELECT JOB,SUM(SAL) AS TOTAL_SALARY
FROM EMP
GROUP BY JOB
HAVING SUM(SAL)>10000;
 
-- 19. Departments with Average Commission Above 500
SELECT D.DNAME AS DEPARTMENT,AVG(E.COMM) AS  AVG_COMMISSION
FROM EMP E
RIGHT JOIN DEPT D
ON E.DEPTNO=D.DEPTNO
GROUP BY D.DNAME
HAVING AVG(COMM) >500;

 
-- 20. Jobs with at Least 3 Employees
SELECT JOB,COUNT(EMPNO)
FROM EMP
GROUP BY JOB
HAVING COUNT(EMPNO)>=3;
  

-- 21-30: Salary Grades and Departments  
-- 21. Salary Grade Distribution  
SELECT SG.GRADE AS SALARY_GRADE,D.DNAME AS DEPARTMENT,COUNT(E.EMPNO) AS EMPLOYEE
FROM EMP E
JOIN SALGRADE SG
ON E.SAL BETWEEN SG.LOSAL AND SG.HISAL
LEFT JOIN DEPT D
ON E.DEPTNO=D.DEPTNO
GROUP BY SG.GRADE,D.DNAME
ORDER BY SG.GRADE,D.DNAME;


-- 22. Departments with Employees in Grade 3  
SELECT D.DNAME AS DEPARTMENT,E.ENAME AS EMPLOYEE,SG.GRADE AS SALARY_GRADE
FROM DEPT D
LEFT JOIN EMP E
ON D.DEPTNO=E.DEPTNO
JOIN SALGRADE AS SG
ON E.SAL BETWEEN SG.LOSAL AND SG.HISAL
WHERE SG.GRADE =3;

-- 23. Highest Salary in Each Grade 
SELECT SG.GRADE AS GRADE,MAX(SAL) AS MAX_SALARY
FROM SALGRADE AS SG
JOIN EMP AS E
ON E.SAL BETWEEN SG.LOSAL AND SG.HISAL
GROUP BY SG.GRADE;
 
-- 24. Departments with Grade 1 Employees 
SELECT D.DNAME AS DEPARTMENT,E.ENAME AS EMPLOYEE,SG.GRADE AS SALARY_GRADE
FROM DEPT D
LEFT JOIN EMP E
ON E.DEPTNO=D.DEPTNO
LEFT JOIN SALGRADE AS SG
ON E.SAL BETWEEN SG.LOSAL AND SG.HISAL
WHERE SG.GRADE=1;

-- 25. Grade-wise Average Salary 
SELECT SG.GRADE AS SALRY_GRADE, AVG(E.SAL) AS AVRAGE_SALARY
FROM SALGRADE AS SG
LEFT JOIN EMP E
ON E.SAL BETWEEN SG.LOSAL AND SG.HISAL
GROUP BY SG.GRADE;

-- 26. Count of Employees Per Department in Grade 4
SELECT D.DNAME AS DEPARTMENT,COUNT(EMPNO) AS NO_OF_EMPLOYEE,SG.GRADE AS SALARY_GRADE
FROM EMP E
RIGHT JOIN DEPT D
ON E.DEPTNO=D.DEPTNO
LEFT JOIN SALGRADE AS SG
ON E.SAL BETWEEN SG.LOSAL AND SG.HISAL
WHERE SG.GRADE =4
GROUP BY D.DNAME;

  
-- 27. Departments with Total Salary Above 10000 in Grade 5 
SELECT D.DNAME AS DEPARTMENT,SUM(E.SAL) AS TOTAL_SALARY,SG.GRADE AS SALARY_GRADE
FROM DEPT D
RIGHT JOIN EMP E
ON D.DEPTNO=E.DEPTNO
LEFT JOIN SALGRADE AS SG
ON E.SAL BETWEEN SG.LOSAL AND SG.HISAL
WHERE SG.GRADE=5
GROUP BY D.DNAME
HAVING SUM(E.SAL) >=5000;

-- 28. Jobs with Employees Only in Grade 1  
SELECT E.ENAME AS EMPLOYEE,SG.GRADE AS SALARY_GRADE
FROM EMP E
LEFT JOIN SALGRADE SG
ON E.SAL BETWEEN SG.LOSAL AND SG.HISAL
WHERE SG.GRADE=1;

-- 29. Departments with Maximum Employee Count in Grade 2
SELECT D.DNAME AS DEPARTMENT,COUNT(E.EMPNO) AS MAX_EMPLOYEE,SG.GRADE AS SALGRADE
FROM DEPT D
RIGHT JOIN EMP E
ON D.DEPTNO=E.DEPTNO
LEFT JOIN SALGRADE SG
ON E.SAL BETWEEN SG.LOSAL AND SG.HISAL
WHERE SG.GRADE=2
GROUP BY D.DNAME
HAVING MAX(E.EMPNO);
 
-- 30. Grades with No Employees in a Specific Department  
SELECT E.ENAME AS EMPLOYEE,D.DNAME AS DEPARTMENT,SG.GRADE AS SALARY_GRADE
FROM EMP E
LEFT JOIN DEPT D
ON E.DEPTNO=E.DEPTNO
LEFT JOIN SALGRADE AS SG
ON E.SAL BETWEEN SG.LOSAL AND SG.HISAL
WHERE D.DNAME="Sales" AND GRADE IS NULL;


-- 31-40: Advanced Salary Grade and Department Queries  
-- 31. Highest Grade Reached by Employees in Each Job 
SELECT E.ENAME AS EMPLOYEE,E.JOB AS JOB,MAX(SG.GRADE) AS MAX_GRADE
FROM EMP E
LEFT JOIN DEPT D
ON E.DEPTNO=D.DEPTNO
LEFT JOIN SALGRADE AS SG
ON E.SAL BETWEEN LOSAL AND HISAL
GROUP BY E.ENAME,E.JOB;

 -- 32. Number of Employees in Grade 5 with Commission  
 SELECT SG.GRADE AS SALGRADE,COUNT(E.EMPNO) AS NUMBER_OF_EMPLOYEE,E.COMM AS COMMISSION
 FROM EMP E
 LEFT JOIN SALGRADE SG
 ON E.SAL BETWEEN SG.LOSAL AND SG.HISAL
 WHERE SG.GRADE=5
 GROUP BY SG.GRADE,E.COMM
 HAVING E.COMM IS NULL;
 
 
 -- 33. Departments with Employees in Multiple Grades
 SELECT D.DNAME AS DEPARTMENT,E.ENAME AS EMPLOYEE,COUNT(SG.GRADE) AS SALARY_GRADE
 FROM DEPT D
 RIGHT JOIN EMP E
 ON D.DEPTNO=E.DEPTNO
 LEFT JOIN SALGRADE AS SG
 ON E.SAL BETWEEN SG.LOSAL AND SG.HISAL
 GROUP BY D.DNAME,E.ENAME
 HAVING COUNT(DISTINCT SG.GRADE) >1;
 
-- 34. Jobs with Total Commission Above 500 in Grade 3  
SELECT E.JOB AS JOB,SUM(E.COMM) AS TOTAL_COMMISSION
FROM EMP E
LEFT JOIN SALGRADE AS SG
ON E.SAL BETWEEN SG.LOSAL AND SG.HISAL
WHERE SG.GRADE=3
GROUP BY E.JOB 
HAVING SUM(E.COMM) >500;

-- 35. Grades with Total Salary Above 20000 
SELECT SG.GRADE AS SAL_GRADE,SUM(E.SAL) AS TOTAL_SALARY
FROM EMP E
LEFT JOIN SALGRADE SG
ON E.SAL BETWEEN SG.LOSAL AND SG.HISAL
GROUP BY SG.GRADE
HAVING SUM(SAL)>10000;

-- 36. Jobs with No Employees in Grade 2  
SELECT E.JOB AS JOB,COUNT(E.EMPNO) AS NO_OF_EMPLOYEE,SG.GRADE AS SAL_GRADE
FROM EMP E
LEFT JOIN SALGRADE AS SG
ON E.SAL BETWEEN SG.LOSAL AND SG.HISAL
WHERE SG.GRADE=2
GROUP BY E.JOB,SG.GRADE;

-- 37. Department Locations with Maximum Salary in Grade 3 
SELECT D.DNAME AS DEPARTMENT,D.LOC AS LOCATION,SG.GRADE AS SAL_GRADE,MAX(SAL) AS TOTAL_SALARY
FROM DEPT D
RIGHT JOIN EMP E
ON D.DEPTNO=E.DEPTNO 
LEFT JOIN SALGRADE AS SG
ON E.SAL BETWEEN SG.LOSAL AND SG.HISAL
WHERE SG.GRADE=3
GROUP BY D.DNAME,D.LOC,SG.GRADE;

-- 38. Number of Jobs in Each Department with Salary Grade 5
SELECT D.DNAME AS DEPARTMENT,COUNT(JOB) AS NUMBER_OF_JOB,SG.GRADE AS SALGRADE
FROM DEPT D
RIGHT JOIN EMP E
ON D.DEPTNO=E.DEPTNO
LEFT JOIN SALGRADE SG
ON E.SAL BETWEEN SG.LOSAL AND SG.HISAL
WHERE SG.GRADE=5
GROUP BY D.DNAME, SG.GRADE; 

-- 39. Employees in Grade 1 Across Multiple Departments 
SELECT D.DNAME AS DEPARTMENT,COUNT(E.EMPNO) AS EMPLOYEES,SG.GRADE AS SAL_GRADE
FROM DEPT D
RIGHT JOIN EMP E
ON D.DEPTNO=E.DEPTNO
LEFT JOIN SALGRADE AS SG
ON E.SAL BETWEEN SG.LOSAL AND SG.HISAL
WHERE SG.GRADE=1
GROUP BY D.DNAME,SG.GRADE;

 
-- 40. Locations with Total Employees Greater Than 5 
SELECT D.LOC AS LOCATION,SUM(E.EMPNO) AS NO_OF_EMPLOYEES
FROM DEPT D
RIGHT JOIN EMP E
ON D.DEPTNO=E.DEPTNO
GROUP BY D.LOC
HAVING SUM(E.EMPNO) >5;

-- 41-50: Miscellaneous and Advanced Queries  
-- 41. Departments with Average Commission Less Than 200
SELECT D.DNAME AS DEPARTMENT,AVG(E.COMM) AS AVERAGR_COMMISSION
FROM DEPT D
RIGHT JOIN EMP E
ON D.DEPTNO=E.DEPTNO
WHERE E.COMM IS NOT NULL
GROUP BY D.DNAME
HAVING AVG(E.COMM) <200;
  
-- 42. Highest Salary by Location for Grade 4 Employees
SELECT D.LOC AS LOCATION,SG.GRADE AS SALGRADE,MAX(E.SAL) AS HIGHEST_SALARY
FROM DEPT D
RIGHT JOIN EMP E
ON D.DEPTNO=E.DEPTNO
LEFT JOIN SALGRADE AS SG
ON E.SAL BETWEEN SG.LOSAL AND SG.HISAL
WHERE SG.GRADE=4
GROUP BY D.LOC,SG.GRADE;

  
-- 43. Departments with More Than 2 Jobs in Grade 3 
SELECT D.DNAME AS DEPARTMENT,COUNT(E.JOB) AS JOB,SG.GRADE AS SALGRADE
FROM DEPT D
RIGHT JOIN EMP E
ON D.DEPTNO=E.DEPTNO
INNER JOIN SALGRADE AS SG
ON E.SAL BETWEEN SG.LOSAL AND SG.HISAL
WHERE SG.GRADE=3
GROUP BY D.DNAME,SG.GRADE
HAVING COUNT(E.JOB) >2;
 
-- 44. Jobs with Employees Across All Grades 
SELECT E.ENAME AS EMPLOYEE,E.JOB AS JOBS,SUM(SG.GRADE) AS SALGRADE
FROM EMP E
LEFT JOIN SALGRADE AS SG
ON E.SAL BETWEEN SG.LOSAL AND SG.HISAL
GROUP BY E.ENAME,E.JOB; 

-- 45. Departments with Salaries Exceeding 5000 in Grade 2  
SELECT D.DNAME AS DEPARTMENT,E.SAL AS SALARY,SG.GRADE AS SAL_GRADE
FROM EMP E
LEFT JOIN DEPT D
ON E.DEPTNO=D.DEPTNO
LEFT JOIN SALGRADE AS SG
ON E.SAL BETWEEN SG.LOSAL AND SG.HISAL
WHERE E.SAL >5000 AND SG.GRADE=2;

-- 46. Jobs with Maximum Commission in Grade 1
SELECT E.JOB AS JOBS, SG.GRADE AS SALGRADE,MAX(E.COMM) AS MAX_COMMISSION
  FROM EMP E
  LEFT JOIN SALGRADE AS SG
  ON E.SAL BETWEEN SG.LOSAL AND SG.HISAL
  WHERE SG.GRADE=1
  GROUP BY E.JOB,SG.GRADE;
  
  
-- 47. Locations with Highest Employee Count Across Grades
SELECT D.LOC AS LOCATION,COUNT(E.EMPNO) AS NO_OF_EMPLOYEE,SG.GRADE AS SALGRADE
FROM DEPT D
RIGHT JOIN EMP E
ON D.DEPTNO=E.DEPTNO
LEFT JOIN SALGRADE AS SG
ON E.SAL BETWEEN SG.LOSAL AND SG.HISAL
GROUP BY D.LOC,SG.GRADE
HAVING MAX( DISTINCT E.EMPNO);
  
-- 48. Grades with Minimum Salary Distribution by Department 
SELECT D.DNAME AS DEPARTMENT,SG.GRADE AS GRADE,MIN(E.SAL) AS MINIMUM_SALARY
FROM DEPT D
RIGHT JOIN EMP E
ON D.DEPTNO=E.DEPTNO
LEFT JOIN SALGRADE SG
ON E.SAL BETWEEN SG.LOSAL AND SG.HISAL
GROUP BY D.DNAME,SG.GRADE;
 
-- 49. Department-wise Total Salaries of Employees Across All Grades 
SELECT D.DNAME AS DEPARTMENT,SG.GRADE AS SAL_GRADE,SUM(E.SAL) AS TOTAL_SALARY
FROM DEPT D
RIGHT JOIN EMP E
ON D.DEPTNO=E.DEPTNO
INNER JOIN SALGRADE AS SG
ON E.SAL BETWEEN SG.LOSAL AND SG.HISAL
GROUP BY D.DNAME,SG.GRADE
ORDER BY D.DNAME; 

-- 50. Average Employee Count by Location and Grade 
SELECT D.LOC AS LOCATION,SG.GRADE AS SALGRADE,COUNT(E.EMPNO) AS COUNT_OF_EMPLOYEE
FROM DEPT AS D
RIGHT JOIN EMP E
ON D.DEPTNO=E.DEPTNO
LEFT JOIN SALGRADE SG
ON E.SAL BETWEEN SG.LOSAL AND SG.HISAL
GROUP BY D.LOC,SG.GRADE
HAVING AVG( E.EMPNO);


 