CREATE DATABASE sql_join;
USE sql_join;



CREATE TABLE DEPT (
    DEPT_ID INT PRIMARY KEY,
    DEPT_NAME VARCHAR(50),
    LOCATION VARCHAR(100)
);

CREATE TABLE EMP (
    EMPLOYEE_ID INT PRIMARY KEY,
    EMP_NAME VARCHAR(100),
    JOB VARCHAR(50),
    MGR_ID INT,
    HIREDATE DATE,
    SALARY Decimal(8, 2),
    COMMISSION_PCT Decimal(2, 2),
    DEPT_ID INT,
    FOREIGN KEY (MGR_ID) REFERENCES EMP(EMPLOYEE_ID),
    FOREIGN KEY (DEPT_ID) REFERENCES DEPT(DEPT_ID)
);

CREATE TABLE SALGRADE (
    GRADE CHAR PRIMARY KEY,
    LOSAL Decimal(8, 2),
    HISAL Decimal(8, 2)
);



-----------
-- DEPT table records (5 records)
INSERT INTO DEPT (DEPT_ID, DEPT_NAME, LOCATION) VALUES (10, 'Accounting', 'New York');
INSERT INTO DEPT (DEPT_ID, DEPT_NAME, LOCATION) VALUES (20, 'Research', 'San Francisco');
INSERT INTO DEPT (DEPT_ID, DEPT_NAME, LOCATION) VALUES (30, 'Sales', 'Los Angeles');
INSERT INTO DEPT (DEPT_ID, DEPT_NAME, LOCATION) VALUES (40, 'IT', 'Chicago');
INSERT INTO DEPT (DEPT_ID, DEPT_NAME, LOCATION) VALUES (50, 'HR', 'Boston');

-- SALGRADE table records (5 records)
INSERT INTO SALGRADE (GRADE, LOSAL, HISAL) VALUES (1, 1000, 2000);
INSERT INTO SALGRADE (GRADE, LOSAL, HISAL) VALUES (2, 2001, 3000);
INSERT INTO SALGRADE (GRADE, LOSAL, HISAL) VALUES (3, 3001, 4000);
INSERT INTO SALGRADE (GRADE, LOSAL, HISAL) VALUES (4, 4001, 5000);
INSERT INTO SALGRADE (GRADE, LOSAL, HISAL) VALUES (5, 5001, 6000);

-- EMP table records 
INSERT INTO EMP (EMPLOYEE_ID, EMP_NAME, JOB, MGR_ID, HIREDATE, SALARY, COMMISSION_PCT, DEPT_ID)
VALUES (100, 'John Smith', 'Clerk', NULL, TO_DATE('2020-01-15', 'YYYY-MM-DD'), 1500, NULL, 10);
INSERT INTO EMP (EMPLOYEE_ID, EMP_NAME, JOB, MGR_ID, HIREDATE, SALARY, COMMISSION_PCT, DEPT_ID)
VALUES (101, 'Alice Brown', 'Manager', 100, TO_DATE('2015-06-23', 'YYYY-MM-DD'), 5000, 0.05, 10);
INSERT INTO EMP (EMPLOYEE_ID, EMP_NAME, JOB, MGR_ID, HIREDATE, SALARY, COMMISSION_PCT, DEPT_ID)
VALUES (102, 'Bob Green', 'Developer', 101, TO_DATE('2018-11-01', 'YYYY-MM-DD'), 4500, NULL, 40);
INSERT INTO EMP (EMPLOYEE_ID, EMP_NAME, JOB, MGR_ID, HIREDATE, SALARY, COMMISSION_PCT, DEPT_ID)
VALUES (103, 'Charlie White', 'Analyst', 102, TO_DATE('2019-03-10', 'YYYY-MM-DD'), 4000, NULL, 20);
INSERT INTO EMP (EMPLOYEE_ID, EMP_NAME, JOB, MGR_ID, HIREDATE, SALARY, COMMISSION_PCT, DEPT_ID)
VALUES (104, 'Daisy Black', 'HR Specialist', 101, TO_DATE('2021-04-10', 'YYYY-MM-DD'), 3000, NULL, 50);

------
-- Inner join Example:
SELECT*FROM emp;
SELECT 
    EMP.EMPLOYEE_ID, 
    EMP.EMP_NAME, 
    EMP.JOB, 
    DEPT.DEPT_NAME, 
    DEPT.LOCATION
FROM 
    EMP
INNER JOIN 
    DEPT ON EMP.DEPT_ID = DEPT.DEPT_ID;

----

-- Left join example:

SELECT 
    EMP.EMPLOYEE_ID, 
    EMP.EMP_NAME, 
    EMP.JOB, 
    DEPT.DEPT_NAME, 
    DEPT.LOCATION
FROM 
    EMP
LEFT JOIN 
    DEPT ON EMP.DEPT_ID = DEPT.DEPT_ID;

-- ight Join Example
SELECT 
    EMP.EMPLOYEE_ID, 
    EMP.EMP_NAME, 
    EMP.JOB, 
    DEPT.DEPT_NAME, 
    DEPT.LOCATION
FROM 
    EMP
RIGHT JOIN 
    DEPT ON EMP.DEPT_ID = DEPT.DEPT_ID;

-- Full Join Example
SELECT 
    EMP.EMPLOYEE_ID, 
    EMP.EMP_NAME, 
    EMP.JOB, 
    DEPT.DEPT_NAME, 
    DEPT.LOCATION
FROM 
    EMP
FULL OUTER JOIN 
    DEPT ON EMP.DEPT_ID = DEPT.DEPT_ID;

