USE join_sql;
SELECT*FROM dept;
SELECT*FROM emp;
SELECT*FROM salgrade;

-- SINGLE ROW SUBQUERY
-- WEITE A QUERY TO FIND THE NAME OF THE EMPLOYEE WITH THE HIGHEST SALARY IN THE COMPANY
SELECT ENAME AS EMPLOYEE,SAL AS SALARY
FROM EMP E
WHERE SAL= (SELECT  MAX(SAL) FROM EMP);

-- FIND THE OLDEST EMPLOYEE
-- WRITE A QUERY TO FIND THE NAME OF THE EMPLOYEE WHO HAS BEEN WORKING IN THE COMPANY FOR THE LONGEST TIME
SELECT ENAME AS EMPLOYEE,HIREDATE
FROM EMP E
WHERE HIREDATE=(SELECT MIN(HIREDATE) FROM EMP);

-- FIND THE MOST HIGHEST SALARY
-- WRITE A QUERY TO FIND THE NAME OF THE EMPLOYEE WITH THE HIGHEST SALARY IN THE PRODUCTS TABLE
SELECT ENAME AS EMPLOYEE,SAL AS SALARY
FROM EMP E
WHERE SAL =(SELECT MAX(SAL) FROM EMP);

-- WRITE A QUERY TO FIND THE NAME OF EMPLOYEE WITH THE LOWEST SALARY
SELECT ENAME AS EMPLOYEE,SAL AS SALARY
FROM EMP E
WHERE SAL=(SELECT MIN(SAL) FROM EMP);

-- WRITE  A QUERY TO FIND THE EMPLOYEE WHO IS RECENTLY HIGHER IN THE COMPANY
SELECT ENAME AS EMPLOYEE,HIREDATE
FROM EMP E
WHERE HIREDATE=(SELECT MAX(HIREDATE) FROM EMP);

-- MULTI ROW SUBQUERY
-- WRITE A QUERY TO FIND THE NAMES OF EMPLOYEE WORKING IN DEPARTMENT LOCATION IN "NEW YORK"
SELECT ENAME AS EMPLOYEE,DEPTNO AS DEPARTMENT_NUMBER
FROM EMP E
WHERE DEPTNO=(SELECT DEPTNO FROM DEPT WHERE LOC="NEW YORK");

-- WRITE A QUERY TO FIND THE NAMES OF EMPLOYEE WHOSE SALARIES FALL WITHIN THE SALARY RANGE OF GRADE 3 IN THE SALGRADE TABLE
SELECT ENAME AS EMPLOYEE,SAL AS SALARY
FROM EMP E
WHERE SAL BETWEEN (SELECT LOSAL FROM SALGRADE WHERE GRADE=3)
AND 
(SELECT HISAL FROM SALGRADE WHERE GRADE=3);

-- WRITE A QUERY TO FIND THE NAMES OF DEPARTMENT THAT HAVE MORE THAN FIVE EMPLOYEE
SELECT DNAME AS DEPARTMENT
FROM DEPT D
WHERE DEPTNO IN (SELECT DEPTNO FROM EMP 
					GROUP BY DEPTNO
                    HAVING COUNT(*)> 5);
                    
-- WRITE A QUERY TO FIND THE NAME OF EMPLOYEE WHO SALARY IS HIGHER THAN THE AVERAGE SALARY OF THE RESPECTIVE DEPARTMENT
SELECT ENAME AS EMPLOYEE,SAL AS SALARY
FROM EMP E
WHERE SAL > (SELECT AVG(SAL) FROM EMP WHERE DEPTNO=E.DEPTNO);

-- WRITE THE QUERY TO FIND THE NAMES OF EMPLOYEE WORKING IN DEPARTMENT THAT DO NOT HAVE MANEGER
SELECT ENAME AS EMPLOYEE
FROM EMP E
WHERE DEPTNO=(SELECT DEPTNO FROM DEPT
					WHERE DEPTNO NOT IN(SELECT DISTINCT DEPTNO
                    FROM EMP 
                    WHERE MGR IS NOT NULL));

                    

